# Generated by Django 3.1 on 2020-09-12 09:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200905_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='image',
        ),
        migrations.AddField(
            model_name='setting',
            name='company',
            field=models.CharField(default=0, max_length=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='references',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='smtemail',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtpassword',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtport',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtserver',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='fax',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=155),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=222),
        ),
    ]
